/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MYPROG_H_RPCGEN
#define _MYPROG_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef struct {
	u_int SensorsArray_len;
	struct SensorData *SensorsArray_val;
} SensorsArray;

struct SensorData {
	int dataId;
	int noValues;
	struct {
		u_int values_len;
		float *values_val;
	} values;
};
typedef struct SensorData SensorData;

struct GetData {
	int sensor;
	int session;
};
typedef struct GetData GetData;

struct PostData {
	int session;
	SensorData sensor;
};
typedef struct PostData PostData;

struct SensorStat {
	int min;
	int max;
	int middle;
	int median;
};
typedef struct SensorStat SensorStat;

struct UserSpace {
	int session;
	char *username;
	SensorData bd;
};
typedef struct UserSpace UserSpace;

#define RPCBD 123456789
#define RPCBDvers 1

#if defined(__STDC__) || defined(__cplusplus)
#define login 1
extern  int * login_1(char **, CLIENT *);
extern  int * login_1_svc(char **, struct svc_req *);
#define logout 2
extern  int * logout_1(int *, CLIENT *);
extern  int * logout_1_svc(int *, struct svc_req *);
#define load 3
extern  void * load_1(UserSpace *, CLIENT *);
extern  void * load_1_svc(UserSpace *, struct svc_req *);
#define add 4
extern  int * add_1(PostData *, CLIENT *);
extern  int * add_1_svc(PostData *, struct svc_req *);
#define delete 5
extern  int * delete_1(GetData *, CLIENT *);
extern  int * delete_1_svc(GetData *, struct svc_req *);
#define update 6
extern  int * update_1(PostData *, CLIENT *);
extern  int * update_1_svc(PostData *, struct svc_req *);
#define read 7
extern  SensorData * read_1(GetData *, CLIENT *);
extern  SensorData * read_1_svc(GetData *, struct svc_req *);
#define readAll 8
extern  SensorsArray * readall_1(int *, CLIENT *);
extern  SensorsArray * readall_1_svc(int *, struct svc_req *);
#define getStat 9
extern  SensorData * getstat_1(GetData *, CLIENT *);
extern  SensorData * getstat_1_svc(GetData *, struct svc_req *);
#define getStatAll 10
extern  SensorData * getstatall_1(int *, CLIENT *);
extern  SensorData * getstatall_1_svc(int *, struct svc_req *);
extern int rpcbd_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define login 1
extern  int * login_1();
extern  int * login_1_svc();
#define logout 2
extern  int * logout_1();
extern  int * logout_1_svc();
#define load 3
extern  void * load_1();
extern  void * load_1_svc();
#define add 4
extern  int * add_1();
extern  int * add_1_svc();
#define delete 5
extern  int * delete_1();
extern  int * delete_1_svc();
#define update 6
extern  int * update_1();
extern  int * update_1_svc();
#define read 7
extern  SensorData * read_1();
extern  SensorData * read_1_svc();
#define readAll 8
extern  SensorsArray * readall_1();
extern  SensorsArray * readall_1_svc();
#define getStat 9
extern  SensorData * getstat_1();
extern  SensorData * getstat_1_svc();
#define getStatAll 10
extern  SensorData * getstatall_1();
extern  SensorData * getstatall_1_svc();
extern int rpcbd_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_SensorsArray (XDR *, SensorsArray*);
extern  bool_t xdr_SensorData (XDR *, SensorData*);
extern  bool_t xdr_GetData (XDR *, GetData*);
extern  bool_t xdr_PostData (XDR *, PostData*);
extern  bool_t xdr_SensorStat (XDR *, SensorStat*);
extern  bool_t xdr_UserSpace (XDR *, UserSpace*);

#else /* K&R C */
extern bool_t xdr_SensorsArray ();
extern bool_t xdr_SensorData ();
extern bool_t xdr_GetData ();
extern bool_t xdr_PostData ();
extern bool_t xdr_SensorStat ();
extern bool_t xdr_UserSpace ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MYPROG_H_RPCGEN */
