/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "myprog.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
rpcbd_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		char *login_1_arg;
		int logout_1_arg;
		UserSpace load_1_arg;
		PostData add_1_arg;
		GetData delete_1_arg;
		PostData update_1_arg;
		GetData read_1_arg;
		int readall_1_arg;
		GetData getstat_1_arg;
		int getstatall_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case login:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) login_1_svc;
		break;

	case logout:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) logout_1_svc;
		break;

	case load:
		_xdr_argument = (xdrproc_t) xdr_UserSpace;
		_xdr_result = (xdrproc_t) xdr_void;
		local = (char *(*)(char *, struct svc_req *)) load_1_svc;
		break;

	case add:
		_xdr_argument = (xdrproc_t) xdr_PostData;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) add_1_svc;
		break;

	case delete:
		_xdr_argument = (xdrproc_t) xdr_GetData;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) delete_1_svc;
		break;

	case update:
		_xdr_argument = (xdrproc_t) xdr_PostData;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) update_1_svc;
		break;

	case read:
		_xdr_argument = (xdrproc_t) xdr_GetData;
		_xdr_result = (xdrproc_t) xdr_SensorData;
		local = (char *(*)(char *, struct svc_req *)) read_1_svc;
		break;

	case readAll:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_SensorsArray;
		local = (char *(*)(char *, struct svc_req *)) readall_1_svc;
		break;

	case getStat:
		_xdr_argument = (xdrproc_t) xdr_GetData;
		_xdr_result = (xdrproc_t) xdr_SensorData;
		local = (char *(*)(char *, struct svc_req *)) getstat_1_svc;
		break;

	case getStatAll:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_SensorData;
		local = (char *(*)(char *, struct svc_req *)) getstatall_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (RPCBD, RPCBDvers);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, RPCBD, RPCBDvers, rpcbd_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (RPCBD, RPCBDvers, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, RPCBD, RPCBDvers, rpcbd_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (RPCBD, RPCBDvers, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
