/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "myprog.h"
#include <string.h>
#include <stdio.h>

void rpcbd_1(char *host, FILE *testFile, char *bdName)
{
	CLIENT *clnt;
	int *result_1;
	char *login_1_arg;
	int *result_2;
	int logout_1_arg;
	void *result_3;
	UserSpace load_1_arg;
	int *result_4;
	PostData add_1_arg;
	int *result_5;
	GetData delete_1_arg;
	int *result_6;
	PostData update_1_arg;
	SensorData *result_7;
	GetData read_1_arg;
	SensorsArray *result_8;
	int readall_1_arg;
	SensorData *result_9;
	GetData getstat_1_arg;
	SensorData *result_10;
	int getstatall_1_arg;
	char clientCommand[20];
	int clientInput;
	int lockedLoad = 0;
	char username[50];
	int session;
	printf("Comanda este  \n");
#ifndef DEBUG
	clnt = clnt_create(host, RPCBD, RPCBDvers, "udp");
	if (clnt == NULL)
	{
		clnt_pcreateerror(host);
		exit(1);
	}
#endif /* DEBUG */

	fscanf(testFile, "%s", clientCommand);

	//printf("Comanda este %s\n", clientCommand);
	while (strcmp(clientCommand, "logout") != 0)
	{
		if (strcmp(clientCommand, "login"))
		{
			fscanf(testFile, "%s", username);

			strcpy(login_1_arg, username);
			result_1 = login_1(&login_1_arg, clnt);
			if (result_1 == (int *)NULL)
			{
				clnt_perror(clnt, "This user is already logged in !");
			}
			else
			{
				session = *result_1;
			}
		}
		if (strcmp(clientCommand, "load"))
		{
		}
		if (strcmp(clientCommand, "store"))
		{
		}
		if (strcmp(clientCommand, "add"))
		{
		}
		if (strcmp(clientCommand, "del"))
		{
		}
		if (strcmp(clientCommand, "update"))
		{
		}
		if (strcmp(clientCommand, "read"))
		{
		}
		if (strcmp(clientCommand, "read_all"))
		{
		}
		if (strcmp(clientCommand, "get_stat"))
		{
		}
		if (strcmp(clientCommand, "get_stat_all"))
		{
		}
	}
	// result_1 = login_1(&login_1_arg, clnt);
	// if (result_1 == (int *)NULL)
	// {
	// 	clnt_perror(clnt, "call failed");
	// }
	// result_2 = logout_1(&logout_1_arg, clnt);
	// if (result_2 == (int *)NULL)
	// {
	// 	clnt_perror(clnt, "call failed");
	// }
	// result_3 = load_1(&load_1_arg, clnt);
	// if (result_3 == (void *)NULL)
	// {
	// 	clnt_perror(clnt, "call failed");
	// }
	// result_4 = add_1(&add_1_arg, clnt);
	// if (result_4 == (int *)NULL)
	// {
	// 	clnt_perror(clnt, "call failed");
	// }
	// result_5 = delete_1(&delete_1_arg, clnt);
	// if (result_5 == (int *)NULL)
	// {
	// 	clnt_perror(clnt, "call failed");
	// }
	// result_6 = update_1(&update_1_arg, clnt);
	// if (result_6 == (int *)NULL)
	// {
	// 	clnt_perror(clnt, "call failed");
	// }
	// result_7 = read_1(&read_1_arg, clnt);
	// if (result_7 == (SensorData *)NULL)
	// {
	// 	clnt_perror(clnt, "call failed");
	// }
	// result_8 = readall_1(&readall_1_arg, clnt);
	// if (result_8 == (SensorsArray *)NULL)
	// {
	// 	clnt_perror(clnt, "call failed");
	// }
	// result_9 = getstat_1(&getstat_1_arg, clnt);
	// if (result_9 == (SensorData *)NULL)
	// {
	// 	clnt_perror(clnt, "call failed");
	// }
	// result_10 = getstatall_1(&getstatall_1_arg, clnt);
	// if (result_10 == (SensorData *)NULL)
	// {
	// 	clnt_perror(clnt, "call failed");
	// }

#ifndef DEBUG
	clnt_destroy(clnt);
#endif /* DEBUG */
	return;
}

int main(int argc, char *argv[])
{
	char *host;
	char username[50] = "VladP";
	char dbName[50] = "VladP.rpcbd.txt";
	FILE *bdFile, *testFile;

	if (argc < 2)
	{
		printf("Al doilea parametru trebuie sa fie o adresa de server valida!\n");
		exit(1);
	}
	//printf("Comanda este ");
	if (argc < 3)
	{
		printf("Al treilea parametru trebuie sa fie fisierul de test\n");
		exit(1);
	}
	if (argc < 4)
	{
		printf("Fisierul pentru baza de date va fi generat automat !\n");
	}
	else
	{
		strcpy(dbName, argv[3]);
	}
	//Creare fisier db in caz ca nu exista
	bdFile = fopen(dbName, "w");
	fclose(bdFile);

	testFile = fopen(argv[2], "r");
	host = argv[1];

	rpcbd_1(host, testFile, dbName);

	fclose(testFile);

	exit(0);
}
