/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "myprog.h"

int *login_1_svc(char **argp, struct svc_req *rqstp)
{
	static int result;

	/*
	 * insert server code here
	 */

	return &result;
};

int *logout_1_svc(int *argp, struct svc_req *rqstp)
{
	static int result;

	/*
	 * insert server code here
	 */

	return &result;
};

void *
load_1_svc(UserSpace *argp, struct svc_req *rqstp)
{
	static char *result;

	/*
	 * insert server code here
	 */

	return (void *)&result;
};

int *add_1_svc(PostData *argp, struct svc_req *rqstp)
{
	static int result;

	/*
	 * insert server code here
	 */

	return &result;
};

int *delete_1_svc(GetData *argp, struct svc_req *rqstp)
{
	static int result;

	/*
	 * insert server code here
	 */

	return &result;
};

int *update_1_svc(PostData *argp, struct svc_req *rqstp)
{
	static int result;

	/*
	 * insert server code here
	 */

	return &result;
};

SensorData *
read_1_svc(GetData *argp, struct svc_req *rqstp)
{
	static SensorData result;

	/*
	 * insert server code here
	 */

	return &result;
};

SensorsArray *
readall_1_svc(int *argp, struct svc_req *rqstp)
{
	static SensorsArray result;

	/*
	 * insert server code here
	 */

	return &result;
};

SensorData *
getstat_1_svc(GetData *argp, struct svc_req *rqstp)
{
	static SensorData result;

	/*
	 * insert server code here
	 */

	return &result;
};

SensorData *
getstatall_1_svc(int *argp, struct svc_req *rqstp)
{
	static SensorData result;

	/*
	 * insert server code here
	 */

	return &result;
};
